apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  annotations:
    deployment.gateway.networking.k8s.io/replicas: "2"
    istio.io/for-service-account: bookinfo-productpage
  name: bookinfo-productpage
spec:
  gatewayClassName: istio-waypoint
  listeners:
  - name: mesh
    port: 15008
    protocol: HBONE
